# Site settings
title: HELLO WORLD
SEOTitle: Hello World | 和菜头
header-img: img/about_workEnv.jpeg
email: west_20@163.com
description: "Every failure is leading towards success."
keyword: "hello,hello,helloworld"
url: "http://WestGG.github.io" 
baseurl: "" 
github_repo: "https://github.com/WestGG/WestGG.github.io.git" 

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Stay hunger,Stay foolish!"
sidebar-avatar: /img/about-me.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:     WestGG




# Build settings
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

